export const AUTH_FORM = {
    STEP_ONE: 'Шаг 1. Личная информация',
    STEP_TWO: 'Шаг 2. Логин и пароль',
    LOGIN_LABEL: 'Логин для входа на сайт',
    LOGIN_PLACEHOLDER: 'Введите логин',
    PASSWORD_LABEL: 'Пароль',
    PASSWORD_PLACEHOLDER: 'Пароль для сайта',
    FORGOT_LOGIN_PASSWORD: 'Забыли логин или пароль?',
    NAME_LABEL: 'Ваше имя',
    NAME_PLACEHOLDER: 'Имя',
    LAST_NAME_LABEL: 'Ваша фамилия',
    LAST_NAME_PLACEHOLDER: 'Фамилия',
    EMAIL_LABEL: 'Ваш e-mail',
    EMAIL_PLACEHOLDER: 'e-mail',
    LOGIN_PLACEHOLDER_SHORT: 'Логин',
    LOGIN_PROMPT: 'Логин не менее 5 символов, только латиница',
    PASSWORD_PLACEHOLDER_SHORT: 'Пароль',
    PASSWORD_PROMPT: 'Пароль не менее 8 символов, с заглавной буквой и цифрой',
    CONFIRM_PASSWORD_LABEL: 'Повторите пароль',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Повторите пароль',
};
