export const DATA_TEST_ID = {
    HEADER: 'header',
    CLOSE_ICON: 'close-icon',
    HAMBURGER_ICON: 'hamburger-icon',
    BREADCRUMBS: 'breadcrumbs',
    NAV: 'nav',
    CARD_LINK: 'card-link',
    LOAD_MORE_BUTTON: 'load-more-button',
    FOOD_CARD: 'food-card',
    INCREMENT_STEPPER: 'increment-stepper',
    DECREMENT_STEPPER: 'decrement-stepper',
    INGREDIENT_QUANTITY: 'ingredient-quantity',
    FILTER_DRAWER: 'filter-drawer',
    CLOSE_FILTER_DRAWER: 'close-filter-drawer',
    FILTER_MENU_BUTTON_CATEGORY: 'filter-menu-button-категория',
    ALLERGENS_SWITCHER_FILTER: 'allergens-switcher-filter',
    ALLERGENS_MENU_BUTTON_FILTER: 'allergens-menu-button-filter',
    FILTER_TAG: 'filter-tag',
    CLEAR_FILTER_BUTTON: 'clear-filter-button',
    FIND_RECIPE_BUTTON: 'find-recipe-button',
    ERROR_NOTIFICATION: 'error-notification',
    CLOSE_ALERT_BUTTON: 'close-alert-button',
    ALLERGENS_MENU: 'allergens-menu',
    ADD_OTHER_ALLERGEN: 'add-other-allergen',
    ADD_ALLERGEN_BUTTON: 'add-allergen-button',
    APP_LOADER: 'app-loader',
    FILTER_BUTTON: 'filter-button',
    SEARCH_INPUT: 'search-input',
    SEARCH_BUTTON: 'search-button',
    CAROUSEL_BACK: 'carousel-back',
    CAROUSEL: 'carousel',
    CAROUSEL_CARD: 'carousel-card',
    CAROUSEL_FORWARD: 'carousel-forward',
    SING_IN_FORM: 'sign-in-form',
    LOGIN_INPUT: 'login-input',
    PASSWORD_INPUT: 'password-input',
    PASSWORD_VISIBILITY_BUTTON: 'password-visibility-button',
    SUBMIT_BUTTON: 'submit-button',
    FORGOT_PASSWORD: 'forgot-password',
    SIGN_IN_ERROR_MODAL: 'sign-in-error-modal',
    CLOSE_BUTTON: 'close-button',
    REPEAT_BUTTON: 'repeat-button',
    SIGN_UP_PROGRESS: 'sign-up-progress',
    FIRST_NAME_INPUT: 'first-name-input',
    LAST_NAME_INPUT: 'last-name-input',
    EMAIL_INPUT: 'email-input',
    SING_UP_PROGRESS: 'sign-up-progress',
    SIGN_UP_FORM: 'sign-up-form',
    CONFIRM_PASSWORD_INPUT: 'confirm-password-input',
    SIGN_UP_SUCCESS_MODAL: 'sign-up-success-modal',
    EMAIL_VERIFICATION_FAILED_MODAL: 'email-verification-failed-modal',
    SEND_EMAIL_MODAL: 'send-email-modal',
    VERIFICATION_CODE_MODAL: 'verification-code-modal',
    VERIFICATION_CODE_INPUT: 'verification-code-input-',
    RESET_CREDENTIALS_MODAL: 'reset-credentials-modal',
    JUICIEST_LINK: 'juiciest-link',
    JUICIEST_LINK_MOBILE: 'juiciest-link-mobile',
    RECIPE_IMAGE_BLOCK: 'recipe-image-block',
    RECIPE_IMAGE_BLOCK_INPUT_FILE: 'recipe-image-block-input-file',
    RECIPE_CATEGORIES: 'recipe-categories',
    RECIPE_TITLE: 'recipe-title',
    RECIPE_DESCRIPTION: 'recipe-description',
    RECIPE_PORTIONS: 'recipe-portions',
    RECIPE_TIME: 'recipe-time',
    RECIPE_SAVE_DRAFT_BUTTON: 'recipe-save-draft-button',
    RECIPE_PUBLISH_RECIPE_BUTTON: 'recipe-publish-recipe-button',
    RECIPE_INGREDIENTS_ADD_INGREDIENTS: 'recipe-ingredients-add-ingredients',
    RECIPE_IMAGE_BLOCK_PREVIEW_IMAGE: 'recipe-image-block-preview-image',
    RECIPE_IMAGE_MODAL: 'recipe-image-modal',
    RECIPE_IMAGE_MODAL_IMAGE_BLOCK: 'recipe-image-modal-image-block',
    RECIPE_IMAGE_MODAL_PREVIEW_IMAGE: 'recipe-image-modal-preview-image',
    RECIPE_PREVENTIVE_MODAL: 'recipe-preventive-modal',
    RECIPE_DELETE_BUTTON: 'recipe-delete-button',
    HEADER_LOGO: 'header-logo',
    ADD_RECIPE_BUTTON: 'add-recipe-button',
    RECIPE_FORM: 'recipe-form',
    MAIN_PAGE_BLOGS_BOX: 'main-page-blogs-box',
    MAIN_PAGE_BLOGS_BUTTON: 'main-page-blogs-button',
    MAIN_PAGE_BLOGS_GRID: 'main-page-blogs-grid',
    BLOGS_CARD: 'blogs-card',
    BLOGS_CARD_NAME: 'blogs-card-name',
    BLOGS_CARD_LOGIN: 'blogs-card-login',
    BLOGS_CARD_NOTES_TEXT: 'blogs-card-notes-text',
    BLOGS_CARD_NEW_RECIPES_BADGE: 'blogs-card-new-recipes-badge',
    BLOGS_CARD_RECIPES_BUTTON: 'blogs-card-recipes-button',
    BLOGS_CARD_NOTES_BUTTON: 'blogs-card-notes-button',
    BLOGS_FAVORITES_BOX: 'blogs-favorites-box',
    BLOGS_FAVORITES_GRID: 'blogs-favorites-grid',
    BLOGS_OTHERS_BOX: 'blogs-others-box',
    BLOGS_OTHERS_GRID: 'blogs-others-grid',
    BLOGS_OTHERS_BUTTON: 'blogs-others-button',
    BLOGGER_USER_INFO_BOX: 'blogger-user-info-box',
    RECIPE_CARD_LIST: 'recipe-card-list',
    BLOG_NOTES_BOX: 'blog-notes-box',
    BLOGGER_USER_INFO_NAME: 'blogger-user-info-name',
    BLOGGER_USER_INFO_LOGIN: 'blogger-user-info-login',
    BLOGGER_FOLLOWERS_COUNT: 'blogger-followers-count',
    BLOGGER_FOLLOWERS_BOOKMARKS: 'blogger-followers-bookmarks',
    BLOGGER_USER_NOTES_COUNT: 'blogger-user-notes-count',
    BLOGGER_USER_NOTES_GRID: 'blogger-user-notes-grid',
    BLOGGER_USER_NOTES_BUTTON: 'blogger-user-notes-button',
    NOTES_CARD_DATE: 'notes-card-date',
    NOTES_CARD_TEXT: 'notes-card-text',
    BLOGGER_USER_OTHER_BLOGS_BUTTON: 'blogger-user-other-blogs-button',
    BLOGGER_USER_OTHER_BLOGS_GRID: 'blogger-user-other-blogs-grid',
    BLOG_TOGGLE_SUBSCRIBE: 'blog-toggle-subscribe',
    BLOG_TOGGLE_UNSUBSCRIBE: 'blog-toggle-unsubscribe',
    BLOGGER_USER_BREADCRUMB_NAME: 'blogger-user-breadcrumb-name',
    BLOGGER_USER_BREADCRUMB_SECTION: 'blogger-user-breadcrumb-section',
    ERROR_NOTIFICATION_TITLE: 'error-notification-title',
    ERROR_NOTIFICATION_DESCRIPTION: 'error-notification-description',
    BLOG_TOOLTIP: 'blog-tooltip',
    MOBILE_LOADER: 'mobile-loader',
    getRecipeIngredientTitle: (order: number) => `recipe-ingredients-title-${order}`,
    getRecipeIngredientCount: (order: number) => `recipe-ingredients-count-${order}`,
    getRecipeIngredientMeasureUnit: (order: number) => `recipe-ingredients-measureUnit-${order}`,
    getRecipeStepImageBlock: (order: number) => `recipe-steps-image-block-${order}`,
    getRecipeStepImageBlockInputFile: (order: number) =>
        `recipe-steps-image-block-${order}-input-file`,
    getRecipeStepDescription: (order: number) => `recipe-steps-description-${order}`,
    getRecipeIngredientsRemoveIngredients: (order: number) =>
        `recipe-ingredients-remove-ingredients-${order}`,
    getRecipeStepsImageBlockPreviewImage: (order: number) =>
        `recipe-steps-image-block-${order}-preview-image`,
    getRecipeStepsRemoveButton: (order: number) => `recipe-steps-remove-button-${order}`,
};
