export const DATA_TEST_ID = {
    HEADER: 'header',
    CLOSE_ICON: 'close-icon',
    HAMBURGER_ICON: 'hamburger-icon',
    BREADCRUMBS: 'breadcrumbs',
    NAV: 'nav',
    CARD_LINK: 'card-link',
    LOAD_MORE_BUTTON: 'load-more-button',
    FOOD_CARD: 'food-card',
    INCREMENT_STEPPER: 'increment-stepper',
    DECREMENT_STEPPER: 'decrement-stepper',
    INGREDIENT_QUANTITY: 'ingredient-quantity',
    FILTER_DRAWER: 'filter-drawer',
    CLOSE_FILTER_DRAWER: 'close-filter-drawer',
    FILTER_MENU_BUTTON_CATEGORY: 'filter-menu-button-категория',
    ALLERGENS_SWITCHER_FILTER: 'allergens-switcher-filter',
    ALLERGENS_MENU_BUTTON_FILTER: 'allergens-menu-button-filter',
    FILTER_TAG: 'filter-tag',
    CLEAR_FILTER_BUTTON: 'clear-filter-button',
    FIND_RECIPE_BUTTON: 'find-recipe-button',
    ERROR_NOTIFICATION: 'error-notification',
    CLOSE_ALERT_BUTTON: 'close-alert-button',
    ALLERGENS_MENU: 'allergens-menu',
    ADD_OTHER_ALLERGEN: 'add-other-allergen',
    ADD_ALLERGEN_BUTTON: 'add-allergen-button',
    APP_LOADER: 'app-loader',
    FILTER_BUTTON: 'filter-button',
    SEARCH_INPUT: 'search-input',
    SEARCH_BUTTON: 'search-button',
    CAROUSEL_BACK: 'carousel-back',
    CAROUSEL: 'carousel',
    CAROUSEL_CARD: 'carousel-card',
    CAROUSEL_FORWARD: 'carousel-forward',
    SING_IN_FORM: 'sign-in-form',
    LOGIN_INPUT: 'login-input',
    PASSWORD_INPUT: 'password-input',
    PASSWORD_VISIBILITY_BUTTON: 'password-visibility-button',
    SUBMIT_BUTTON: 'submit-button',
    FORGOT_PASSWORD: 'forgot-password',
    SIGN_IN_ERROR_MODAL: 'sign-in-error-modal',
    CLOSE_BUTTON: 'close-button',
    REPEAT_BUTTON: 'repeat-button',
    SIGN_UP_PROGRESS: 'sign-up-progress',
    FIRST_NAME_INPUT: 'first-name-input',
    LAST_NAME_INPUT: 'last-name-input',
    EMAIL_INPUT: 'email-input',
    SING_UP_PROGRESS: 'sign-up-progress',
    SIGN_UP_FORM: 'sign-up-form',
    CONFIRM_PASSWORD_INPUT: 'confirm-password-input',
    SIGN_UP_SUCCESS_MODAL: 'sign-up-success-modal',
    EMAIL_VERIFICATION_FAILED_MODAL: 'email-verification-failed-modal',
    SEND_EMAIL_MODAL: 'send-email-modal',
    VERIFICATION_CODE_MODAL: 'verification-code-modal',
    VERIFICATION_CODE_INPUT: 'verification-code-input-',
    RESET_CREDENTIALS_MODAL: 'reset-credentials-modal',
    JUICIEST_LINK: 'juiciest-link',
    JUICIEST_LINK_MOBILE: 'juiciest-link-mobile',
    RECIPE_IMAGE_BLOCK: 'recipe-image-block',
    RECIPE_IMAGE_BLOCK_INPUT_FILE: 'recipe-image-block-input-file',
    RECIPE_CATEGORIES: 'recipe-categories',
    RECIPE_TITLE: 'recipe-title',
    RECIPE_DESCRIPTION: 'recipe-description',
    RECIPE_PORTIONS: 'recipe-portions',
    RECIPE_TIME: 'recipe-time',
    RECIPE_SAVE_DRAFT_BUTTON: 'recipe-save-draft-button',
    RECIPE_PUBLISH_RECIPE_BUTTON: 'recipe-publish-recipe-button',
    RECIPE_INGREDIENTS_ADD_INGREDIENTS: 'recipe-ingredients-add-ingredients',
    RECIPE_IMAGE_BLOCK_PREVIEW_IMAGE: 'recipe-image-block-preview-image',
    RECIPE_IMAGE_MODAL: 'recipe-image-modal',
    RECIPE_IMAGE_MODAL_IMAGE_BLOCK: 'recipe-image-modal-image-block',
    RECIPE_IMAGE_MODAL_PREVIEW_IMAGE: 'recipe-image-modal-preview-image',
    RECIPE_PREVENTIVE_MODAL: 'recipe-preventive-modal',
    RECIPE_DELETE_BUTTON: 'recipe-delete-button',
    HEADER_LOGO: 'header-logo',
    ADD_RECIPE_BUTTON: 'add-recipe-button',
    RECIPE_FORM: 'recipe-form',
    getRecipeIngredientTitle: (order: number) => `recipe-ingredients-title-${order}`,
    getRecipeIngredientCount: (order: number) => `recipe-ingredients-count-${order}`,
    getRecipeIngredientMeasureUnit: (order: number) => `recipe-ingredients-measureUnit-${order}`,
    getRecipeStepImageBlock: (order: number) => `recipe-steps-image-block-${order}`,
    getRecipeStepImageBlockInputFile: (order: number) =>
        `recipe-steps-image-block-${order}-input-file`,
    getRecipeStepDescription: (order: number) => `recipe-steps-description-${order}`,
    getRecipeIngredientsRemoveIngredients: (order: number) =>
        `recipe-ingredients-remove-ingredients-${order}`,
    getRecipeStepsImageBlockPreviewImage: (order: number) =>
        `recipe-steps-image-block-${order}-preview-image`,
    getRecipeStepsRemoveButton: (order: number) => `recipe-steps-remove-button-${order}`,
};
