export const VALIDATY = {
    ERR_REQUIRED_LOGIN: 'Введите логин',
    ERR_REQUIRED_PASSWORD: 'Введите пароль',
    ERR_REQUIRED_PASSWORD_CONFIRM: 'Повторите пароль',
    ERR_REQUIRED_EMAIL: 'Введите e-mail',
    ERR_REQUIRED_FIRST_NAME: 'Введите имя',
    ERR_REQUIRED_LAST_NAME: 'Введите фамилию',
    ERR_MAX_LENGTH: 'Максимальная длина 50 символов',
    ERR_INVALID_FORMAT: 'Не соответствует формату',
    ERR_PASSWORD_MISMATCH: 'Пароли должны совпадать',
    ERR_INVALID_EMAIL: 'Введите корректный e-mail',
    ERR_FIRST_LETTER_CYRILLIC: 'Должно начинаться с кириллицы А-Я',
    ERR_ONLY_CYRILLIC: 'Только кириллица А-Я, и "-"',
    REGEX_LOGIN: /^[A-Za-z!@#$&_+\-.]+$/,
    REGEX_PASSWORD: /^(?=.*\d)(?=.*[A-Z])[A-Za-z\d!@#$&_+\-.]+$/,
    REGEX_EMAIL: /\.[A-Za-z]{2,}$/,
    REGEX_FIRST_LETTER_CYRILLIC: /^[А-Я]/,
    REGEX_ONLY_CYRILLIC: /^[А-Я][а-я-]*$/,
};
