export const PATH = {
    CATEGORY: 'category',
    RECIPE: 'recipe',
    AUTH_REFRESH: 'auth/refresh',
    AUTH_CHECK_AUTH: 'auth/check-auth',
    AUTH_SIGNUP: 'auth/signup',
    AUTH_LOGIN: 'auth/login',
    AUTH_FORGOT_PASSWORD: 'auth/forgot-password',
    AUTH_VERIFY_OTP: 'auth/verify-otp',
    AUTH_RESET_PASSWORD: 'auth/reset-password',
    MEASURE_INITS: 'measure-units',
    FILE_UPLOAD: 'file/upload',
    DRAFT: 'draft',
    LIKE: 'like',
    BOOKMARK: 'bookmark',
};
